remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: "New Year, New You"
description: "Frank P Leuck and Judith Sherwood Leuck reunion site and blog."
gitorg: "https://github.com/haeryny/teamteam"
description: "Become your best self in 2023!"
google_analytics:
exclude: /path