theme: jekyll-theme-midnight
title: "New Year, New You"
description: "June 26 to July 1 2023"
gitorg: "https://github.com/haeryny/teamteam"
google_analytics:
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme
# title: "New Year, New You"
# description: "Become your best self in 2023!"
# gitorg: "https://github.com/haeryny/teamteam"
# google_analytics:
# exclude: /path